--- 
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: web
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: application
  serviceName: application
  template: 
    metadata: 
      labels: 
        app: application
    spec: 
      containers: 
        - 
          image: "registry:2.7.1"
          livenessProbe: 
            initialDelaySeconds: 10
            tcpSocket: 
              port: 5000
          name: application
          ports: 
            - 
              containerPort: 5000
              name: web
              protocol: TCP
          readinessProbe: 
            tcpSocket: 
              port: 5000
            initialDelaySeconds: 10  
          volumeMounts: 
            - 
              mountPath: /var/lib/registry
              name: www
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates: 
    - 
      metadata: 
        name: www
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 100Gi
        storageClassName: my-storage-class
